-- Fichier généré par scripts/generate-seed.ts — ne pas modifier à la main.
begin;

insert into public.frameworks (id, name, short_name, version, description) values
  ('iso27001', 'ISO/IEC 27001:2022', 'ISO 27001', '2022', 'Norme internationale de management de la sécurité de l''information (SMSI). Certifiable par un organisme accrédité.'),
  ('nis2', 'Directive NIS2 (UE 2022/2555)', 'NIS2', '2022/2555', 'Directive européenne de cybersécurité, transposée en France par la loi Résilience. Contrôlée par l''ANSSI.')
on conflict (id) do update set name = excluded.name, short_name = excluded.short_name, version = excluded.version, description = excluded.description;

insert into public.requirements (id, framework_id, ref, title, sort) values
  ('iso27001:4.1', 'iso27001', '§4.1', 'Comprendre l''organisation et son contexte', 0),
  ('iso27001:4.2', 'iso27001', '§4.2', 'Comprendre les attentes des parties intéressées', 1),
  ('iso27001:4.3', 'iso27001', '§4.3', 'Définir le périmètre du SMSI', 2),
  ('iso27001:4.4', 'iso27001', '§4.4', 'Établir et faire vivre le SMSI', 3),
  ('iso27001:5.1', 'iso27001', '§5.1', 'Leadership et engagement de la direction', 4),
  ('iso27001:5.2', 'iso27001', '§5.2', 'Politique de sécurité de l''information', 5),
  ('iso27001:5.3', 'iso27001', '§5.3', 'Rôles, responsabilités et autorités', 6),
  ('iso27001:6.1', 'iso27001', '§6.1', 'Appréciation et traitement des risques', 7),
  ('iso27001:6.2', 'iso27001', '§6.2', 'Objectifs de sécurité et plans pour les atteindre', 8),
  ('iso27001:6.3', 'iso27001', '§6.3', 'Planification des modifications', 9),
  ('iso27001:7.1', 'iso27001', '§7.1', 'Ressources', 10),
  ('iso27001:7.2', 'iso27001', '§7.2', 'Compétences', 11),
  ('iso27001:7.3', 'iso27001', '§7.3', 'Sensibilisation', 12),
  ('iso27001:7.4', 'iso27001', '§7.4', 'Communication', 13),
  ('iso27001:7.5', 'iso27001', '§7.5', 'Informations documentées', 14),
  ('iso27001:8.1', 'iso27001', '§8.1', 'Planification et maîtrise opérationnelles', 15),
  ('iso27001:8.2', 'iso27001', '§8.2', 'Réalisation de l''appréciation des risques', 16),
  ('iso27001:8.3', 'iso27001', '§8.3', 'Mise en œuvre du traitement des risques', 17),
  ('iso27001:9.1', 'iso27001', '§9.1', 'Surveillance, mesure, analyse et évaluation', 18),
  ('iso27001:9.2', 'iso27001', '§9.2', 'Audit interne', 19),
  ('iso27001:9.3', 'iso27001', '§9.3', 'Revue de direction', 20),
  ('iso27001:10.1', 'iso27001', '§10.1', 'Amélioration continue', 21),
  ('iso27001:10.2', 'iso27001', '§10.2', 'Non-conformités et actions correctives', 22),
  ('iso27001:A.5.1', 'iso27001', 'A.5.1', 'Politiques de sécurité de l''information', 100),
  ('iso27001:A.5.2', 'iso27001', 'A.5.2', 'Rôles et responsabilités en sécurité', 101),
  ('iso27001:A.5.3', 'iso27001', 'A.5.3', 'Séparation des tâches', 102),
  ('iso27001:A.5.4', 'iso27001', 'A.5.4', 'Responsabilités de la direction', 103),
  ('iso27001:A.5.5', 'iso27001', 'A.5.5', 'Relations avec les autorités', 104),
  ('iso27001:A.5.6', 'iso27001', 'A.5.6', 'Relations avec des groupes spécialisés', 105),
  ('iso27001:A.5.7', 'iso27001', 'A.5.7', 'Veille sur les menaces', 106),
  ('iso27001:A.5.8', 'iso27001', 'A.5.8', 'Sécurité dans la gestion de projet', 107),
  ('iso27001:A.5.9', 'iso27001', 'A.5.9', 'Inventaire des informations et des actifs', 108),
  ('iso27001:A.5.10', 'iso27001', 'A.5.10', 'Utilisation acceptable des actifs', 109),
  ('iso27001:A.5.11', 'iso27001', 'A.5.11', 'Restitution des actifs', 110),
  ('iso27001:A.5.12', 'iso27001', 'A.5.12', 'Classification des informations', 111),
  ('iso27001:A.5.13', 'iso27001', 'A.5.13', 'Marquage des informations', 112),
  ('iso27001:A.5.14', 'iso27001', 'A.5.14', 'Transfert des informations', 113),
  ('iso27001:A.5.15', 'iso27001', 'A.5.15', 'Contrôle d''accès', 114),
  ('iso27001:A.5.16', 'iso27001', 'A.5.16', 'Gestion des identités', 115),
  ('iso27001:A.5.17', 'iso27001', 'A.5.17', 'Informations d''authentification', 116),
  ('iso27001:A.5.18', 'iso27001', 'A.5.18', 'Droits d''accès', 117),
  ('iso27001:A.5.19', 'iso27001', 'A.5.19', 'Sécurité dans les relations fournisseurs', 118),
  ('iso27001:A.5.20', 'iso27001', 'A.5.20', 'Sécurité dans les contrats fournisseurs', 119),
  ('iso27001:A.5.21', 'iso27001', 'A.5.21', 'Sécurité de la chaîne d''approvisionnement informatique', 120),
  ('iso27001:A.5.22', 'iso27001', 'A.5.22', 'Suivi et revue des services fournisseurs', 121),
  ('iso27001:A.5.23', 'iso27001', 'A.5.23', 'Sécurité des services cloud', 122),
  ('iso27001:A.5.24', 'iso27001', 'A.5.24', 'Préparation à la gestion des incidents', 123),
  ('iso27001:A.5.25', 'iso27001', 'A.5.25', 'Évaluation des événements de sécurité', 124),
  ('iso27001:A.5.26', 'iso27001', 'A.5.26', 'Réponse aux incidents de sécurité', 125),
  ('iso27001:A.5.27', 'iso27001', 'A.5.27', 'Retour d''expérience sur les incidents', 126),
  ('iso27001:A.5.28', 'iso27001', 'A.5.28', 'Collecte des preuves', 127),
  ('iso27001:A.5.29', 'iso27001', 'A.5.29', 'Sécurité pendant une perturbation', 128),
  ('iso27001:A.5.30', 'iso27001', 'A.5.30', 'Préparation des TIC à la continuité d''activité', 129),
  ('iso27001:A.5.31', 'iso27001', 'A.5.31', 'Exigences légales, réglementaires et contractuelles', 130),
  ('iso27001:A.5.32', 'iso27001', 'A.5.32', 'Droits de propriété intellectuelle', 131),
  ('iso27001:A.5.33', 'iso27001', 'A.5.33', 'Protection des enregistrements', 132),
  ('iso27001:A.5.34', 'iso27001', 'A.5.34', 'Vie privée et protection des données personnelles', 133),
  ('iso27001:A.5.35', 'iso27001', 'A.5.35', 'Revue indépendante de la sécurité', 134),
  ('iso27001:A.5.36', 'iso27001', 'A.5.36', 'Conformité aux politiques et règles internes', 135),
  ('iso27001:A.5.37', 'iso27001', 'A.5.37', 'Procédures d''exploitation documentées', 136),
  ('iso27001:A.6.1', 'iso27001', 'A.6.1', 'Vérifications avant embauche', 137),
  ('iso27001:A.6.2', 'iso27001', 'A.6.2', 'Clauses du contrat de travail', 138),
  ('iso27001:A.6.3', 'iso27001', 'A.6.3', 'Sensibilisation et formation à la sécurité', 139),
  ('iso27001:A.6.4', 'iso27001', 'A.6.4', 'Processus disciplinaire', 140),
  ('iso27001:A.6.5', 'iso27001', 'A.6.5', 'Responsabilités après départ ou changement de poste', 141),
  ('iso27001:A.6.6', 'iso27001', 'A.6.6', 'Accords de confidentialité', 142),
  ('iso27001:A.6.7', 'iso27001', 'A.6.7', 'Travail à distance', 143),
  ('iso27001:A.6.8', 'iso27001', 'A.6.8', 'Signalement des événements de sécurité', 144),
  ('iso27001:A.7.1', 'iso27001', 'A.7.1', 'Périmètres de sécurité physique', 145),
  ('iso27001:A.7.2', 'iso27001', 'A.7.2', 'Contrôle des entrées physiques', 146),
  ('iso27001:A.7.3', 'iso27001', 'A.7.3', 'Sécurisation des bureaux, salles et équipements', 147),
  ('iso27001:A.7.4', 'iso27001', 'A.7.4', 'Surveillance de la sécurité physique', 148),
  ('iso27001:A.7.5', 'iso27001', 'A.7.5', 'Protection contre les menaces physiques et environnementales', 149),
  ('iso27001:A.7.6', 'iso27001', 'A.7.6', 'Travail dans les zones sécurisées', 150),
  ('iso27001:A.7.7', 'iso27001', 'A.7.7', 'Bureau propre et écran verrouillé', 151),
  ('iso27001:A.7.8', 'iso27001', 'A.7.8', 'Emplacement et protection du matériel', 152),
  ('iso27001:A.7.9', 'iso27001', 'A.7.9', 'Sécurité des actifs hors des locaux', 153),
  ('iso27001:A.7.10', 'iso27001', 'A.7.10', 'Supports de stockage', 154),
  ('iso27001:A.7.11', 'iso27001', 'A.7.11', 'Services généraux (électricité, climatisation…)', 155),
  ('iso27001:A.7.12', 'iso27001', 'A.7.12', 'Sécurité du câblage', 156),
  ('iso27001:A.7.13', 'iso27001', 'A.7.13', 'Maintenance du matériel', 157),
  ('iso27001:A.7.14', 'iso27001', 'A.7.14', 'Mise au rebut ou réutilisation sécurisée du matériel', 158),
  ('iso27001:A.8.1', 'iso27001', 'A.8.1', 'Terminaux des utilisateurs', 159),
  ('iso27001:A.8.2', 'iso27001', 'A.8.2', 'Droits d''accès à privilèges', 160),
  ('iso27001:A.8.3', 'iso27001', 'A.8.3', 'Restriction d''accès aux informations', 161),
  ('iso27001:A.8.4', 'iso27001', 'A.8.4', 'Accès au code source', 162),
  ('iso27001:A.8.5', 'iso27001', 'A.8.5', 'Authentification sécurisée', 163),
  ('iso27001:A.8.6', 'iso27001', 'A.8.6', 'Gestion des capacités', 164),
  ('iso27001:A.8.7', 'iso27001', 'A.8.7', 'Protection contre les logiciels malveillants', 165),
  ('iso27001:A.8.8', 'iso27001', 'A.8.8', 'Gestion des vulnérabilités techniques', 166),
  ('iso27001:A.8.9', 'iso27001', 'A.8.9', 'Gestion des configurations', 167),
  ('iso27001:A.8.10', 'iso27001', 'A.8.10', 'Suppression des informations', 168),
  ('iso27001:A.8.11', 'iso27001', 'A.8.11', 'Masquage des données', 169),
  ('iso27001:A.8.12', 'iso27001', 'A.8.12', 'Prévention des fuites de données', 170),
  ('iso27001:A.8.13', 'iso27001', 'A.8.13', 'Sauvegarde des informations', 171),
  ('iso27001:A.8.14', 'iso27001', 'A.8.14', 'Redondance des moyens de traitement', 172),
  ('iso27001:A.8.15', 'iso27001', 'A.8.15', 'Journalisation', 173),
  ('iso27001:A.8.16', 'iso27001', 'A.8.16', 'Surveillance des activités', 174),
  ('iso27001:A.8.17', 'iso27001', 'A.8.17', 'Synchronisation des horloges', 175),
  ('iso27001:A.8.18', 'iso27001', 'A.8.18', 'Utilitaires à privilèges', 176),
  ('iso27001:A.8.19', 'iso27001', 'A.8.19', 'Installation de logiciels sur les systèmes en production', 177),
  ('iso27001:A.8.20', 'iso27001', 'A.8.20', 'Sécurité des réseaux', 178),
  ('iso27001:A.8.21', 'iso27001', 'A.8.21', 'Sécurité des services réseau', 179),
  ('iso27001:A.8.22', 'iso27001', 'A.8.22', 'Cloisonnement des réseaux', 180),
  ('iso27001:A.8.23', 'iso27001', 'A.8.23', 'Filtrage web', 181),
  ('iso27001:A.8.24', 'iso27001', 'A.8.24', 'Utilisation de la cryptographie', 182),
  ('iso27001:A.8.25', 'iso27001', 'A.8.25', 'Cycle de développement sécurisé', 183),
  ('iso27001:A.8.26', 'iso27001', 'A.8.26', 'Exigences de sécurité des applications', 184),
  ('iso27001:A.8.27', 'iso27001', 'A.8.27', 'Architecture et principes d''ingénierie sécurisés', 185),
  ('iso27001:A.8.28', 'iso27001', 'A.8.28', 'Codage sécurisé', 186),
  ('iso27001:A.8.29', 'iso27001', 'A.8.29', 'Tests de sécurité en développement et recette', 187),
  ('iso27001:A.8.30', 'iso27001', 'A.8.30', 'Développement externalisé', 188),
  ('iso27001:A.8.31', 'iso27001', 'A.8.31', 'Séparation des environnements dev, test et production', 189),
  ('iso27001:A.8.32', 'iso27001', 'A.8.32', 'Gestion des changements', 190),
  ('iso27001:A.8.33', 'iso27001', 'A.8.33', 'Données de test', 191),
  ('iso27001:A.8.34', 'iso27001', 'A.8.34', 'Protection des systèmes pendant les audits', 192),
  ('nis2:20.1', 'nis2', 'Art. 20 §1', 'Approbation et supervision des mesures par les dirigeants', 0),
  ('nis2:20.2', 'nis2', 'Art. 20 §2', 'Formation à la cybersécurité des dirigeants', 1),
  ('nis2:21.2.a', 'nis2', 'Art. 21 §2 a)', 'Analyse des risques et politiques de sécurité des SI', 2),
  ('nis2:21.2.b', 'nis2', 'Art. 21 §2 b)', 'Gestion des incidents', 3),
  ('nis2:21.2.c', 'nis2', 'Art. 21 §2 c)', 'Continuité d''activité : sauvegardes, reprise, gestion de crise', 4),
  ('nis2:21.2.d', 'nis2', 'Art. 21 §2 d)', 'Sécurité de la chaîne d''approvisionnement', 5),
  ('nis2:21.2.e', 'nis2', 'Art. 21 §2 e)', 'Sécurité de l''acquisition, du développement et de la maintenance, gestion des vulnérabilités', 6),
  ('nis2:21.2.f', 'nis2', 'Art. 21 §2 f)', 'Évaluation de l''efficacité des mesures', 7),
  ('nis2:21.2.g', 'nis2', 'Art. 21 §2 g)', 'Cyberhygiène de base et formation', 8),
  ('nis2:21.2.h', 'nis2', 'Art. 21 §2 h)', 'Cryptographie et chiffrement', 9),
  ('nis2:21.2.i', 'nis2', 'Art. 21 §2 i)', 'Sécurité RH, contrôle d''accès et gestion des actifs', 10),
  ('nis2:21.2.j', 'nis2', 'Art. 21 §2 j)', 'Authentification multifacteur et communications sécurisées', 11),
  ('nis2:23', 'nis2', 'Art. 23', 'Notification des incidents importants (24 h / 72 h / 1 mois)', 12),
  ('nis2:27', 'nis2', 'Art. 27', 'Enregistrement auprès de l''autorité nationale (ANSSI)', 13)
on conflict (id) do update set ref = excluded.ref, title = excluded.title, sort = excluded.sort;

insert into public.controls (id, title, en_clair, theme, priority, applicability_tags, evidence_examples, review_days, sort) values
  ('SMSI.4', 'Contexte et périmètre du SMSI', 'Décrire votre activité, vos parties prenantes (clients, autorités…) et ce que couvre votre démarche de sécurité.', 'gouvernance', 'socle', '{}'::text[], array['Note de contexte et de périmètre', 'Liste des parties intéressées et de leurs attentes']::text[], 365, 0),
  ('SMSI.5', 'Engagement de la direction et politique', 'La direction porte la démarche, approuve la politique et les moyens, et en rend compte.', 'gouvernance', 'socle', '{}'::text[], array['Politique signée par la direction', 'Décision de lancement de la démarche']::text[], 365, 1),
  ('SMSI.5.3', 'Rôles et responsabilités du SMSI', 'Nommer un responsable de la démarche et préciser qui rend compte à la direction.', 'gouvernance', 'socle', '{}'::text[], array['Lettre de nomination du responsable sécurité', 'Organigramme du SMSI']::text[], 365, 2),
  ('SMSI.6.1', 'Appréciation et traitement des risques', 'Lister ce qui pourrait mal tourner, évaluer la gravité et la probabilité, et décider quoi faire pour chaque risque.', 'gouvernance', 'socle', '{}'::text[], array['Registre des risques', 'Plan de traitement des risques validé']::text[], 365, 3),
  ('SMSI.SOA', 'Déclaration d''applicabilité', 'Le document qui liste toutes les mesures de l''annexe A, dit lesquelles vous appliquez et justifie les exclusions. Il est généré automatiquement par l''outil.', 'gouvernance', 'socle', '{}'::text[], array['Déclaration d''applicabilité exportée et signée']::text[], 365, 4),
  ('SMSI.6.2', 'Objectifs de sécurité', 'Fixer quelques objectifs mesurables (ex. 100 % des postes à jour) et planifier les changements.', 'gouvernance', 'standard', '{}'::text[], array['Tableau des objectifs avec indicateurs', 'Plan d''action daté']::text[], 365, 5),
  ('SMSI.7', 'Ressources, compétences et communication', 'Vérifier que les personnes impliquées ont le temps et les compétences, et organiser la communication sur la sécurité.', 'gouvernance', 'standard', '{}'::text[], array['Matrice de compétences', 'Plan de communication interne']::text[], 365, 6),
  ('SMSI.7.3', 'Sensibilisation au SMSI', 'Chacun connaît la politique de sécurité et sait ce qu''on attend de lui.', 'gouvernance', 'standard', '{}'::text[], array['Attestations de lecture de la politique']::text[], 365, 7),
  ('SMSI.7.5', 'Documentation et maîtrise opérationnelle', 'Tenir à jour les documents de la démarche (versions, validations) et appliquer ce qui est prévu.', 'gouvernance', 'standard', '{}'::text[], array['Liste des documents avec version et date', 'Historique des validations']::text[], 365, 8),
  ('SMSI.9.1', 'Indicateurs et suivi', 'Suivre quelques indicateurs (score de conformité, incidents, formations) pour mesurer les progrès.', 'gouvernance', 'standard', '{}'::text[], array['Tableau de bord des indicateurs (export de l''outil)']::text[], 180, 9),
  ('SMSI.9.2', 'Audit interne', 'Vérifier au moins une fois par an que la démarche fonctionne, avant l''auditeur externe.', 'gouvernance', 'standard', '{}'::text[], array['Programme d''audit interne', 'Rapport d''audit interne']::text[], 365, 10),
  ('SMSI.9.3', 'Revue de direction', 'Une réunion annuelle où la direction fait le point et prend des décisions sur la sécurité.', 'gouvernance', 'standard', '{}'::text[], array['Compte rendu de revue de direction signé']::text[], 365, 11),
  ('SMSI.10', 'Amélioration et actions correctives', 'Traiter les écarts constatés, corriger leurs causes et suivre les actions jusqu''au bout.', 'gouvernance', 'standard', '{}'::text[], array['Registre des non-conformités et actions correctives']::text[], 180, 12),
  ('NIS2.20', 'Formation des dirigeants à la cybersécurité', 'Les dirigeants suivent une formation pour comprendre les risques cyber et les décisions qu''ils doivent prendre.', 'gouvernance', 'socle', array['nis2']::text[], array['Attestation de formation des dirigeants']::text[], 365, 13),
  ('NIS2.23', 'Notification des incidents à l''ANSSI', 'Savoir notifier un incident important : alerte sous 24 h, notification sous 72 h, rapport final sous 1 mois.', 'gouvernance', 'socle', array['nis2']::text[], array['Procédure de notification', 'Test ou exercice de notification réalisé']::text[], 365, 14),
  ('NIS2.27', 'Enregistrement auprès de l''ANSSI', 'S''enregistrer sur MonEspaceNIS2 et tenir les informations à jour.', 'gouvernance', 'socle', array['nis2']::text[], array['Capture de l''enregistrement sur MonEspaceNIS2']::text[], 365, 15),
  ('A.5.1', 'Politiques de sécurité de l''information', 'Écrire une politique de sécurité courte, validée et signée par la direction, et la communiquer à tous.', 'organisationnel', 'socle', '{}'::text[], array['Politique de sécurité signée par le dirigeant', 'Preuve de diffusion (email, affichage, accusé de lecture)']::text[], 365, 16),
  ('A.5.2', 'Rôles et responsabilités en sécurité', 'Désigner qui s''occupe de quoi en sécurité (référent interne, prestataire informatique, dirigeant).', 'organisationnel', 'socle', '{}'::text[], array['Organigramme sécurité ou fiche de poste du référent', 'Contrat du prestataire informatique précisant son rôle']::text[], 365, 17),
  ('A.5.3', 'Séparation des tâches', 'Éviter qu''une même personne puisse à la fois demander, valider et exécuter une action sensible (ex. paiement, droits d''accès).', 'organisationnel', 'standard', array['salaries']::text[], array['Matrice des validations (qui demande / qui valide)', 'Extrait de paramétrage des droits dans les outils']::text[], 365, 18),
  ('A.5.4', 'Responsabilités de la direction', 'La direction s''assure que chacun applique les règles de sécurité et y consacre les moyens nécessaires.', 'organisationnel', 'standard', '{}'::text[], array['Compte rendu de réunion de direction mentionnant la sécurité', 'Budget ou plan d''action validé']::text[], 365, 19),
  ('A.5.5', 'Relations avec les autorités', 'Savoir qui contacter en cas d''incident : ANSSI/CERT-FR, CNIL, police/gendarmerie, cybermalveillance.gouv.fr.', 'organisationnel', 'standard', '{}'::text[], array['Fiche des contacts d''urgence à jour', 'Procédure indiquant quand contacter chaque autorité']::text[], 365, 20),
  ('A.5.6', 'Relations avec des groupes spécialisés', 'Suivre au moins une source spécialisée (CERT-FR, CLUSIF, fédération professionnelle) pour rester informé.', 'organisationnel', 'standard', '{}'::text[], array['Abonnement à une lettre d''alerte (capture)', 'Participation à un club ou groupe métier']::text[], 365, 21),
  ('A.5.7', 'Veille sur les menaces', 'Surveiller les menaces qui concernent votre activité (alertes CERT-FR, fournisseurs) et en tenir compte.', 'organisationnel', 'standard', '{}'::text[], array['Journal des alertes reçues et des suites données', 'Abonnement aux bulletins de sécurité des éditeurs utilisés']::text[], 365, 22),
  ('A.5.8', 'Sécurité dans la gestion de projet', 'Intégrer une question sécurité dans chaque nouveau projet (nouvel outil, nouveau site, nouvelle machine connectée).', 'organisationnel', 'standard', '{}'::text[], array['Check-list sécurité projet remplie', 'Compte rendu de lancement de projet']::text[], 365, 23),
  ('A.5.9', 'Inventaire des informations et des actifs', 'Tenir une liste à jour de vos équipements, logiciels et données importantes, avec un responsable pour chacun.', 'organisationnel', 'socle', '{}'::text[], array['Inventaire des actifs (tableur ou export outil)', 'Date de dernière mise à jour de l''inventaire']::text[], 365, 24),
  ('A.5.10', 'Utilisation acceptable des actifs', 'Fixer les règles d''usage des outils (ordinateurs, messagerie, Internet) dans une charte connue de tous.', 'organisationnel', 'standard', '{}'::text[], array['Charte informatique signée', 'Annexe au règlement intérieur']::text[], 365, 25),
  ('A.5.11', 'Restitution des actifs', 'Récupérer le matériel, les badges et les clés quand quelqu''un quitte l''entreprise.', 'organisationnel', 'standard', array['salaries']::text[], array['Check-list de départ signée', 'Registre de remise du matériel']::text[], 365, 26),
  ('A.5.12', 'Classification des informations', 'Classer les informations selon leur sensibilité (publique, interne, confidentielle).', 'organisationnel', 'standard', '{}'::text[], array['Règle de classification documentée', 'Exemples de documents classés']::text[], 365, 27),
  ('A.5.13', 'Marquage des informations', 'Indiquer visiblement la sensibilité d''un document (mention « Confidentiel », dossier dédié…).', 'organisationnel', 'standard', '{}'::text[], array['Modèle de document avec mention de classification', 'Photo d''un classeur étiqueté']::text[], 365, 28),
  ('A.5.14', 'Transfert des informations', 'Encadrer l''envoi d''informations (emails, clés USB, transferts de fichiers) pour éviter les fuites.', 'organisationnel', 'standard', '{}'::text[], array['Règle d''échange de fichiers sensibles', 'Outil de transfert sécurisé utilisé (capture)']::text[], 365, 29),
  ('A.5.15', 'Contrôle d''accès', 'Définir qui a accès à quoi, selon le besoin réel de chacun.', 'organisationnel', 'socle', '{}'::text[], array['Politique de contrôle d''accès', 'Tableau des droits par fonction']::text[], 365, 30),
  ('A.5.16', 'Gestion des identités', 'Un compte nominatif par personne, créé à l''arrivée et supprimé au départ.', 'organisationnel', 'standard', '{}'::text[], array['Liste des comptes actifs comparée à la liste du personnel', 'Procédure arrivée/départ']::text[], 365, 31),
  ('A.5.17', 'Informations d''authentification', 'Des mots de passe solides, jamais partagés, stockés dans un gestionnaire de mots de passe.', 'organisationnel', 'socle', '{}'::text[], array['Règle de mots de passe', 'Capture du gestionnaire de mots de passe déployé']::text[], 365, 32),
  ('A.5.18', 'Droits d''accès', 'Revoir régulièrement les droits d''accès et retirer ceux qui ne servent plus.', 'organisationnel', 'standard', '{}'::text[], array['Compte rendu de revue des accès daté', 'Liste des droits retirés']::text[], 180, 33),
  ('A.5.19', 'Sécurité dans les relations fournisseurs', 'Identifier vos fournisseurs critiques (informatique, hébergement, maintenance) et les risques qu''ils représentent.', 'organisationnel', 'socle', '{}'::text[], array['Liste des fournisseurs critiques', 'Questionnaire sécurité rempli par les fournisseurs']::text[], 365, 34),
  ('A.5.20', 'Sécurité dans les contrats fournisseurs', 'Prévoir des clauses de sécurité et de confidentialité dans les contrats fournisseurs.', 'organisationnel', 'standard', '{}'::text[], array['Contrats avec clauses sécurité', 'Accord de sous-traitance RGPD signé']::text[], 365, 35),
  ('A.5.21', 'Sécurité de la chaîne d''approvisionnement informatique', 'S''assurer que le matériel et les logiciels achetés viennent de sources fiables et sont maintenus.', 'organisationnel', 'standard', '{}'::text[], array['Liste des fournisseurs informatiques agréés', 'Contrats de maintenance']::text[], 365, 36),
  ('A.5.22', 'Suivi et revue des services fournisseurs', 'Suivre la qualité et la sécurité des services fournisseurs, et réagir en cas de changement.', 'organisationnel', 'standard', '{}'::text[], array['Compte rendu de revue fournisseur', 'Rapports de service ou certificats reçus']::text[], 365, 37),
  ('A.5.23', 'Sécurité des services cloud', 'Choisir et paramétrer les services cloud (messagerie, stockage, logiciels en ligne) en connaissant les règles de sécurité.', 'organisationnel', 'standard', array['cloud']::text[], array['Liste des services cloud utilisés et leur localisation', 'Certifications des fournisseurs cloud (ISO 27001, HDS…)']::text[], 365, 38),
  ('A.5.24', 'Préparation à la gestion des incidents', 'Préparer à l''avance ce qu''on fait en cas d''incident : qui alerter, qui décide, quelles premières actions.', 'organisationnel', 'socle', '{}'::text[], array['Procédure de gestion des incidents', 'Fiche réflexe affichée ou diffusée']::text[], 365, 39),
  ('A.5.25', 'Évaluation des événements de sécurité', 'Savoir distinguer un simple événement d''un vrai incident, et décider de la suite.', 'organisationnel', 'standard', '{}'::text[], array['Critères de qualification d''un incident', 'Registre des événements analysés']::text[], 365, 40),
  ('A.5.26', 'Réponse aux incidents de sécurité', 'Réagir à un incident selon la procédure prévue et tracer les actions menées.', 'organisationnel', 'standard', '{}'::text[], array['Registre des incidents', 'Compte rendu d''un incident traité']::text[], 365, 41),
  ('A.5.27', 'Retour d''expérience sur les incidents', 'Tirer les leçons de chaque incident pour éviter qu''il se reproduise.', 'organisationnel', 'standard', '{}'::text[], array['Retour d''expérience rédigé', 'Actions correctives issues d''un incident']::text[], 365, 42),
  ('A.5.28', 'Collecte des preuves', 'Conserver les traces utiles (journaux, captures, emails) en cas d''incident, notamment pour un dépôt de plainte.', 'organisationnel', 'standard', '{}'::text[], array['Procédure de conservation des preuves', 'Exemple de dossier d''incident archivé']::text[], 365, 43),
  ('A.5.29', 'Sécurité pendant une perturbation', 'Maintenir un niveau de sécurité minimum même en situation de crise (panne, sinistre, cyberattaque).', 'organisationnel', 'standard', '{}'::text[], array['Plan de continuité mentionnant la sécurité', 'Mode dégradé documenté']::text[], 365, 44),
  ('A.5.30', 'Préparation des TIC à la continuité d''activité', 'Prévoir comment redémarrer l''informatique après un sinistre, et le tester.', 'organisationnel', 'socle', '{}'::text[], array['Plan de reprise informatique', 'Compte rendu de test de restauration']::text[], 365, 45),
  ('A.5.31', 'Exigences légales, réglementaires et contractuelles', 'Lister les obligations légales et contractuelles de sécurité qui s''appliquent à vous (RGPD, NIS2, contrats clients).', 'organisationnel', 'standard', '{}'::text[], array['Registre des exigences légales et contractuelles', 'Revue annuelle datée']::text[], 365, 46),
  ('A.5.32', 'Droits de propriété intellectuelle', 'Utiliser uniquement des logiciels et contenus dont vous avez les licences.', 'organisationnel', 'standard', '{}'::text[], array['Inventaire des licences', 'Factures ou contrats de licence']::text[], 365, 47),
  ('A.5.33', 'Protection des enregistrements', 'Protéger les documents à conserver (factures, contrats, registres) contre la perte et la falsification.', 'organisationnel', 'standard', '{}'::text[], array['Règle de conservation et d''archivage', 'Photo/capture de l''archivage sécurisé']::text[], 365, 48),
  ('A.5.34', 'Vie privée et protection des données personnelles', 'Respecter le RGPD pour les données personnelles (clients, salariés, fournisseurs).', 'organisationnel', 'standard', array['donnees_perso']::text[], array['Registre des traitements RGPD', 'Mentions d''information et politique de confidentialité']::text[], 365, 49),
  ('A.5.35', 'Revue indépendante de la sécurité', 'Faire vérifier votre sécurité par un regard extérieur (audit, prestataire indépendant) de temps en temps.', 'organisationnel', 'standard', '{}'::text[], array['Rapport d''audit externe ou de test d''intrusion', 'Plan de suivi des recommandations']::text[], 365, 50),
  ('A.5.36', 'Conformité aux politiques et règles internes', 'Vérifier que les règles internes de sécurité sont réellement appliquées.', 'organisationnel', 'standard', '{}'::text[], array['Contrôles internes réalisés (check-list datée)', 'Écarts relevés et actions associées']::text[], 365, 51),
  ('A.5.37', 'Procédures d''exploitation documentées', 'Écrire les procédures importantes (sauvegarde, arrivée d''un salarié, mise à jour) pour qu''elles ne dépendent pas d''une seule personne.', 'organisationnel', 'standard', '{}'::text[], array['Procédures d''exploitation documentées', 'Date de dernière mise à jour']::text[], 365, 52),
  ('A.6.1', 'Vérifications avant embauche', 'Vérifier, dans le respect du droit du travail, les informations des candidats à des postes sensibles.', 'humain', 'standard', array['salaries']::text[], array['Procédure de recrutement', 'Check-list de vérifications réalisées']::text[], 365, 53),
  ('A.6.2', 'Clauses du contrat de travail', 'Inclure les obligations de sécurité et de confidentialité dans les contrats de travail.', 'humain', 'standard', array['salaries']::text[], array['Modèle de contrat avec clause de confidentialité', 'Charte informatique annexée']::text[], 365, 54),
  ('A.6.3', 'Sensibilisation et formation à la sécurité', 'Sensibiliser tout le personnel aux bons réflexes (hameçonnage, mots de passe, verrouillage) au moins une fois par an.', 'humain', 'socle', '{}'::text[], array['Feuille d''émargement ou attestation de formation', 'Support de sensibilisation utilisé']::text[], 365, 55),
  ('A.6.4', 'Processus disciplinaire', 'Prévoir les suites en cas de manquement aux règles de sécurité (dans le règlement intérieur).', 'humain', 'standard', array['salaries']::text[], array['Règlement intérieur mentionnant la sécurité', 'Charte informatique signée']::text[], 365, 56),
  ('A.6.5', 'Responsabilités après départ ou changement de poste', 'Rappeler au départ d''un salarié qu''il reste tenu à la confidentialité, et retirer ses accès.', 'humain', 'standard', array['salaries']::text[], array['Check-list de départ signée', 'Preuve de désactivation des comptes']::text[], 365, 57),
  ('A.6.6', 'Accords de confidentialité', 'Faire signer des accords de confidentialité aux personnes et partenaires qui accèdent à des informations sensibles.', 'humain', 'standard', '{}'::text[], array['Accords de confidentialité signés', 'Liste des signataires']::text[], 365, 58),
  ('A.6.7', 'Travail à distance', 'Encadrer le télétravail : poste sécurisé, connexion protégée, confidentialité à domicile.', 'humain', 'standard', '{}'::text[], array['Charte télétravail', 'Configuration VPN ou accès sécurisé']::text[], 365, 59),
  ('A.6.8', 'Signalement des événements de sécurité', 'Chacun sait comment et à qui signaler un comportement suspect ou un incident, sans délai.', 'humain', 'socle', '{}'::text[], array['Procédure de signalement diffusée', 'Adresse ou canal dédié (capture)']::text[], 365, 60),
  ('A.7.1', 'Périmètres de sécurité physique', 'Délimiter les zones à protéger (bureaux, local informatique, atelier) et leurs accès.', 'physique', 'standard', array['locaux']::text[], array['Plan des locaux avec zones', 'Photos des accès sécurisés']::text[], 365, 61),
  ('A.7.2', 'Contrôle des entrées physiques', 'Contrôler qui entre dans les locaux (clés, badges, registre des visiteurs).', 'physique', 'standard', array['locaux']::text[], array['Registre des visiteurs', 'Liste des détenteurs de clés/badges']::text[], 365, 62),
  ('A.7.3', 'Sécurisation des bureaux, salles et équipements', 'Fermer à clé les bureaux et armoires contenant des informations ou du matériel sensibles.', 'physique', 'standard', array['locaux']::text[], array['Photo des armoires et portes verrouillées', 'Règle de fermeture des locaux']::text[], 365, 63),
  ('A.7.4', 'Surveillance de la sécurité physique', 'Surveiller les locaux (alarme, vidéoprotection, gardiennage) selon le niveau de risque.', 'physique', 'standard', array['locaux']::text[], array['Contrat d''alarme ou de télésurveillance', 'Rapport de maintenance du système']::text[], 365, 64),
  ('A.7.5', 'Protection contre les menaces physiques et environnementales', 'Protéger le matériel contre l''incendie, l''eau, la chaleur et les coupures.', 'physique', 'standard', array['locaux']::text[], array['Vérification des extincteurs', 'Photo du local serveur (climatisation, onduleur)']::text[], 365, 65),
  ('A.7.6', 'Travail dans les zones sécurisées', 'Fixer des règles de comportement dans les zones sensibles (pas de visiteur seul, pas de photo…).', 'physique', 'standard', array['locaux']::text[], array['Consignes affichées', 'Règle d''accompagnement des visiteurs']::text[], 365, 66),
  ('A.7.7', 'Bureau propre et écran verrouillé', 'Ne pas laisser de documents sensibles sur les bureaux et verrouiller son écran en s''absentant.', 'physique', 'socle', '{}'::text[], array['Règle bureau propre/écran verrouillé', 'Paramétrage du verrouillage automatique (capture)']::text[], 365, 67),
  ('A.7.8', 'Emplacement et protection du matériel', 'Placer le matériel informatique à l''abri des regards, des chocs et des accès non autorisés.', 'physique', 'standard', array['locaux']::text[], array['Photo de l''emplacement des serveurs/équipements', 'Inventaire avec localisation']::text[], 365, 68),
  ('A.7.9', 'Sécurité des actifs hors des locaux', 'Protéger les ordinateurs et téléphones utilisés à l''extérieur (chiffrement, vigilance en déplacement).', 'physique', 'standard', '{}'::text[], array['Liste du matériel nomade', 'Preuve du chiffrement des portables']::text[], 365, 69),
  ('A.7.10', 'Supports de stockage', 'Encadrer l''usage des clés USB et disques externes, et les effacer avant mise au rebut.', 'physique', 'standard', '{}'::text[], array['Règle d''usage des supports amovibles', 'Registre des supports']::text[], 365, 70),
  ('A.7.11', 'Services généraux (électricité, climatisation…)', 'Assurer l''alimentation électrique et les services nécessaires au matériel (onduleur, climatisation).', 'physique', 'standard', array['locaux']::text[], array['Contrat de maintenance onduleur', 'Test de bascule sur onduleur']::text[], 365, 71),
  ('A.7.12', 'Sécurité du câblage', 'Protéger les câbles réseau et électriques contre les dommages et les branchements pirates.', 'physique', 'standard', array['locaux']::text[], array['Photo de la baie de brassage fermée', 'Plan de câblage']::text[], 365, 72),
  ('A.7.13', 'Maintenance du matériel', 'Entretenir le matériel selon les recommandations du fabricant, avec des intervenants autorisés.', 'physique', 'standard', '{}'::text[], array['Contrats et rapports de maintenance', 'Registre des interventions']::text[], 365, 73),
  ('A.7.14', 'Mise au rebut ou réutilisation sécurisée du matériel', 'Effacer de manière sûre les données avant de jeter, vendre ou réattribuer un équipement.', 'physique', 'standard', '{}'::text[], array['Certificat de destruction ou d''effacement', 'Registre de sortie du matériel']::text[], 365, 74),
  ('A.8.1', 'Terminaux des utilisateurs', 'Sécuriser les ordinateurs et téléphones : mises à jour, antivirus, verrouillage, chiffrement.', 'technologique', 'socle', '{}'::text[], array['Liste des postes avec état de sécurité', 'Capture de la console de gestion des postes']::text[], 365, 75),
  ('A.8.2', 'Droits d''accès à privilèges', 'Limiter les comptes administrateurs au strict nécessaire et les surveiller.', 'technologique', 'socle', '{}'::text[], array['Liste des comptes administrateurs', 'Revue des comptes à privilèges datée']::text[], 180, 76),
  ('A.8.3', 'Restriction d''accès aux informations', 'Chacun n''accède qu''aux dossiers et applications dont il a besoin.', 'technologique', 'standard', '{}'::text[], array['Paramétrage des droits sur les partages', 'Tableau des droits par fonction']::text[], 365, 77),
  ('A.8.4', 'Accès au code source', 'Protéger l''accès au code source (dépôt privé, droits limités, historique).', 'technologique', 'standard', array['dev']::text[], array['Capture des droits du dépôt de code', 'Liste des personnes ayant accès']::text[], 365, 78),
  ('A.8.5', 'Authentification sécurisée', 'Activer la double authentification (MFA) sur la messagerie, les accès à distance et les outils critiques.', 'technologique', 'socle', '{}'::text[], array['Capture de l''activation MFA', 'Liste des services protégés par MFA']::text[], 365, 79),
  ('A.8.6', 'Gestion des capacités', 'Surveiller l''espace disque, la puissance et les ressources pour éviter les saturations.', 'technologique', 'standard', '{}'::text[], array['Tableau de suivi des capacités', 'Alertes de supervision']::text[], 365, 80),
  ('A.8.7', 'Protection contre les logiciels malveillants', 'Installer et maintenir à jour un antivirus/EDR sur tous les postes et serveurs.', 'technologique', 'socle', '{}'::text[], array['Console antivirus montrant les postes protégés', 'Rapport de détection récent']::text[], 365, 81),
  ('A.8.8', 'Gestion des vulnérabilités techniques', 'Appliquer rapidement les mises à jour de sécurité et suivre les failles connues.', 'technologique', 'socle', '{}'::text[], array['Rapport de mises à jour appliquées', 'Scan de vulnérabilités daté']::text[], 90, 82),
  ('A.8.9', 'Gestion des configurations', 'Configurer les équipements de façon sécurisée et garder une trace de ces réglages.', 'technologique', 'standard', '{}'::text[], array['Fiches de configuration de référence', 'Capture des paramètres de sécurité']::text[], 365, 83),
  ('A.8.10', 'Suppression des informations', 'Supprimer les données dont vous n''avez plus besoin, dans les délais prévus.', 'technologique', 'standard', array['donnees_perso']::text[], array['Durées de conservation définies', 'Preuve de purge réalisée']::text[], 365, 84),
  ('A.8.11', 'Masquage des données', 'Masquer ou anonymiser les données sensibles quand leur affichage complet n''est pas nécessaire.', 'technologique', 'standard', array['dev']::text[], array['Règles de masquage', 'Capture d''un écran avec données masquées']::text[], 365, 85),
  ('A.8.12', 'Prévention des fuites de données', 'Limiter les risques de fuite de données (envois externes, partages publics, impressions).', 'technologique', 'standard', '{}'::text[], array['Paramétrage des partages externes', 'Règle de prévention des fuites']::text[], 365, 86),
  ('A.8.13', 'Sauvegarde des informations', 'Sauvegarder régulièrement les données, en garder une copie hors ligne et tester la restauration.', 'technologique', 'socle', '{}'::text[], array['Rapport de sauvegarde récent', 'Compte rendu de test de restauration']::text[], 90, 87),
  ('A.8.14', 'Redondance des moyens de traitement', 'Doubler les éléments indispensables (connexion, serveur, stockage) pour éviter un arrêt total.', 'technologique', 'standard', '{}'::text[], array['Schéma de l''infrastructure redondante', 'Contrat de secours (4G, second lien)']::text[], 365, 88),
  ('A.8.15', 'Journalisation', 'Conserver les journaux d''événements importants (connexions, erreurs, actions d''administration).', 'technologique', 'standard', '{}'::text[], array['Paramétrage de la journalisation', 'Extrait de journal']::text[], 365, 89),
  ('A.8.16', 'Surveillance des activités', 'Surveiller les systèmes pour détecter les comportements anormaux.', 'technologique', 'standard', '{}'::text[], array['Alertes de supervision configurées', 'Rapport de surveillance']::text[], 365, 90),
  ('A.8.17', 'Synchronisation des horloges', 'Régler tous les équipements sur la même heure de référence, pour des journaux cohérents.', 'technologique', 'standard', '{}'::text[], array['Paramétrage NTP (capture)']::text[], 365, 91),
  ('A.8.18', 'Utilitaires à privilèges', 'Réserver les outils système puissants aux administrateurs.', 'technologique', 'standard', '{}'::text[], array['Liste des outils restreints', 'Paramétrage des restrictions']::text[], 365, 92),
  ('A.8.19', 'Installation de logiciels sur les systèmes en production', 'Contrôler l''installation de logiciels sur les postes et serveurs.', 'technologique', 'standard', '{}'::text[], array['Règle d''installation des logiciels', 'Liste des logiciels autorisés']::text[], 365, 93),
  ('A.8.20', 'Sécurité des réseaux', 'Protéger le réseau : pare-feu, Wi-Fi sécurisé, accès distants maîtrisés.', 'technologique', 'standard', '{}'::text[], array['Schéma réseau', 'Configuration du pare-feu et du Wi-Fi']::text[], 365, 94),
  ('A.8.21', 'Sécurité des services réseau', 'Exiger un niveau de sécurité des fournisseurs réseau (box, opérateur, VPN).', 'technologique', 'standard', '{}'::text[], array['Contrat opérateur avec engagements', 'Paramètres de sécurité des services réseau']::text[], 365, 95),
  ('A.8.22', 'Cloisonnement des réseaux', 'Séparer les réseaux (invités, production, bureautique, machines) pour limiter la propagation d''une attaque.', 'technologique', 'standard', '{}'::text[], array['Schéma des réseaux séparés', 'Capture du Wi-Fi invité isolé']::text[], 365, 96),
  ('A.8.23', 'Filtrage web', 'Bloquer l''accès aux sites web dangereux.', 'technologique', 'standard', '{}'::text[], array['Configuration du filtrage web', 'Rapport de sites bloqués']::text[], 365, 97),
  ('A.8.24', 'Utilisation de la cryptographie', 'Chiffrer les données sensibles (disques des portables, sauvegardes, échanges) et protéger les clés.', 'technologique', 'socle', '{}'::text[], array['Preuve du chiffrement des disques', 'Règle d''usage du chiffrement']::text[], 365, 98),
  ('A.8.25', 'Cycle de développement sécurisé', 'Intégrer la sécurité à chaque étape du développement logiciel.', 'technologique', 'standard', array['dev']::text[], array['Processus de développement documenté', 'Revue de sécurité d''une fonctionnalité']::text[], 365, 99),
  ('A.8.26', 'Exigences de sécurité des applications', 'Définir les exigences de sécurité de vos applications avant de les développer ou de les acheter.', 'technologique', 'standard', array['dev']::text[], array['Exigences sécurité dans un cahier des charges', 'Ticket de spécification avec critères sécurité']::text[], 365, 100),
  ('A.8.27', 'Architecture et principes d''ingénierie sécurisés', 'Concevoir les systèmes selon des principes de sécurité reconnus (moindre privilège, défense en profondeur).', 'technologique', 'standard', array['dev']::text[], array['Schéma d''architecture', 'Principes de conception documentés']::text[], 365, 101),
  ('A.8.28', 'Codage sécurisé', 'Appliquer les bonnes pratiques de code sécurisé (validation des entrées, dépendances à jour).', 'technologique', 'standard', array['dev']::text[], array['Règles de codage', 'Rapport d''analyse de code ou de dépendances']::text[], 365, 102),
  ('A.8.29', 'Tests de sécurité en développement et recette', 'Tester la sécurité avant chaque mise en production.', 'technologique', 'standard', array['dev']::text[], array['Résultats de tests de sécurité', 'Rapport de test d''intrusion']::text[], 365, 103),
  ('A.8.30', 'Développement externalisé', 'Encadrer et contrôler la sécurité quand le développement est confié à un prestataire.', 'technologique', 'standard', array['dev']::text[], array['Contrat de développement avec exigences sécurité', 'Recette sécurité du livrable']::text[], 365, 104),
  ('A.8.31', 'Séparation des environnements dev, test et production', 'Séparer les environnements de développement, de test et de production.', 'technologique', 'standard', array['dev']::text[], array['Schéma des environnements', 'Droits d''accès à la production']::text[], 365, 105),
  ('A.8.32', 'Gestion des changements', 'Préparer, valider et tracer les changements importants sur les systèmes.', 'technologique', 'standard', '{}'::text[], array['Registre des changements', 'Exemple de changement validé']::text[], 365, 106),
  ('A.8.33', 'Données de test', 'Ne pas utiliser de vraies données sensibles pour les tests, ou les protéger.', 'technologique', 'standard', array['dev']::text[], array['Règle sur les données de test', 'Jeu de données anonymisé']::text[], 365, 107),
  ('A.8.34', 'Protection des systèmes pendant les audits', 'Organiser les audits techniques pour qu''ils ne perturbent pas l''activité.', 'technologique', 'standard', '{}'::text[], array['Planning d''audit validé', 'Accès temporaire accordé et retiré']::text[], 365, 108)
on conflict (id) do update set title = excluded.title, en_clair = excluded.en_clair, theme = excluded.theme, priority = excluded.priority, applicability_tags = excluded.applicability_tags, evidence_examples = excluded.evidence_examples, review_days = excluded.review_days, sort = excluded.sort;

delete from public.control_requirements;
insert into public.control_requirements (control_id, requirement_id) values
  ('SMSI.4', 'iso27001:4.1'),
  ('SMSI.4', 'iso27001:4.2'),
  ('SMSI.4', 'iso27001:4.3'),
  ('SMSI.4', 'iso27001:4.4'),
  ('SMSI.5', 'iso27001:5.1'),
  ('SMSI.5', 'iso27001:5.2'),
  ('SMSI.5', 'nis2:20.1'),
  ('SMSI.5.3', 'iso27001:5.3'),
  ('SMSI.6.1', 'iso27001:6.1'),
  ('SMSI.6.1', 'iso27001:8.2'),
  ('SMSI.6.1', 'iso27001:8.3'),
  ('SMSI.6.1', 'nis2:21.2.a'),
  ('SMSI.SOA', 'iso27001:6.1'),
  ('SMSI.6.2', 'iso27001:6.2'),
  ('SMSI.6.2', 'iso27001:6.3'),
  ('SMSI.7', 'iso27001:7.1'),
  ('SMSI.7', 'iso27001:7.2'),
  ('SMSI.7', 'iso27001:7.4'),
  ('SMSI.7.3', 'iso27001:7.3'),
  ('SMSI.7.5', 'iso27001:7.5'),
  ('SMSI.7.5', 'iso27001:8.1'),
  ('SMSI.9.1', 'iso27001:9.1'),
  ('SMSI.9.1', 'nis2:21.2.f'),
  ('SMSI.9.2', 'iso27001:9.2'),
  ('SMSI.9.2', 'nis2:21.2.f'),
  ('SMSI.9.3', 'iso27001:9.3'),
  ('SMSI.9.3', 'nis2:20.1'),
  ('SMSI.10', 'iso27001:10.1'),
  ('SMSI.10', 'iso27001:10.2'),
  ('SMSI.10', 'nis2:21.2.f'),
  ('NIS2.20', 'nis2:20.2'),
  ('NIS2.23', 'nis2:23'),
  ('NIS2.23', 'nis2:21.2.b'),
  ('NIS2.27', 'nis2:27'),
  ('A.5.1', 'iso27001:A.5.1'),
  ('A.5.1', 'nis2:21.2.a'),
  ('A.5.1', 'nis2:20.1'),
  ('A.5.2', 'iso27001:A.5.2'),
  ('A.5.2', 'nis2:21.2.a'),
  ('A.5.3', 'iso27001:A.5.3'),
  ('A.5.3', 'nis2:21.2.i'),
  ('A.5.4', 'iso27001:A.5.4'),
  ('A.5.4', 'nis2:20.1'),
  ('A.5.5', 'iso27001:A.5.5'),
  ('A.5.5', 'nis2:21.2.b'),
  ('A.5.6', 'iso27001:A.5.6'),
  ('A.5.7', 'iso27001:A.5.7'),
  ('A.5.7', 'nis2:21.2.e'),
  ('A.5.8', 'iso27001:A.5.8'),
  ('A.5.8', 'nis2:21.2.e'),
  ('A.5.9', 'iso27001:A.5.9'),
  ('A.5.9', 'nis2:21.2.i'),
  ('A.5.10', 'iso27001:A.5.10'),
  ('A.5.10', 'nis2:21.2.g'),
  ('A.5.10', 'nis2:21.2.i'),
  ('A.5.11', 'iso27001:A.5.11'),
  ('A.5.11', 'nis2:21.2.i'),
  ('A.5.12', 'iso27001:A.5.12'),
  ('A.5.12', 'nis2:21.2.i'),
  ('A.5.13', 'iso27001:A.5.13'),
  ('A.5.14', 'iso27001:A.5.14'),
  ('A.5.14', 'nis2:21.2.j'),
  ('A.5.14', 'nis2:21.2.h'),
  ('A.5.15', 'iso27001:A.5.15'),
  ('A.5.15', 'nis2:21.2.i'),
  ('A.5.16', 'iso27001:A.5.16'),
  ('A.5.16', 'nis2:21.2.i'),
  ('A.5.17', 'iso27001:A.5.17'),
  ('A.5.17', 'nis2:21.2.i'),
  ('A.5.17', 'nis2:21.2.j'),
  ('A.5.18', 'iso27001:A.5.18'),
  ('A.5.18', 'nis2:21.2.i'),
  ('A.5.19', 'iso27001:A.5.19'),
  ('A.5.19', 'nis2:21.2.d'),
  ('A.5.20', 'iso27001:A.5.20'),
  ('A.5.20', 'nis2:21.2.d'),
  ('A.5.21', 'iso27001:A.5.21'),
  ('A.5.21', 'nis2:21.2.d'),
  ('A.5.22', 'iso27001:A.5.22'),
  ('A.5.22', 'nis2:21.2.d'),
  ('A.5.23', 'iso27001:A.5.23'),
  ('A.5.23', 'nis2:21.2.d'),
  ('A.5.24', 'iso27001:A.5.24'),
  ('A.5.24', 'nis2:21.2.b'),
  ('A.5.25', 'iso27001:A.5.25'),
  ('A.5.25', 'nis2:21.2.b'),
  ('A.5.26', 'iso27001:A.5.26'),
  ('A.5.26', 'nis2:21.2.b'),
  ('A.5.27', 'iso27001:A.5.27'),
  ('A.5.27', 'nis2:21.2.b'),
  ('A.5.27', 'nis2:21.2.f'),
  ('A.5.28', 'iso27001:A.5.28'),
  ('A.5.28', 'nis2:21.2.b'),
  ('A.5.29', 'iso27001:A.5.29'),
  ('A.5.29', 'nis2:21.2.c'),
  ('A.5.30', 'iso27001:A.5.30'),
  ('A.5.30', 'nis2:21.2.c'),
  ('A.5.31', 'iso27001:A.5.31'),
  ('A.5.31', 'nis2:21.2.a'),
  ('A.5.32', 'iso27001:A.5.32'),
  ('A.5.33', 'iso27001:A.5.33'),
  ('A.5.34', 'iso27001:A.5.34'),
  ('A.5.35', 'iso27001:A.5.35'),
  ('A.5.35', 'nis2:21.2.f'),
  ('A.5.36', 'iso27001:A.5.36'),
  ('A.5.36', 'nis2:21.2.f'),
  ('A.5.37', 'iso27001:A.5.37'),
  ('A.6.1', 'iso27001:A.6.1'),
  ('A.6.1', 'nis2:21.2.i'),
  ('A.6.2', 'iso27001:A.6.2'),
  ('A.6.2', 'nis2:21.2.i'),
  ('A.6.3', 'iso27001:A.6.3'),
  ('A.6.3', 'nis2:21.2.g'),
  ('A.6.4', 'iso27001:A.6.4'),
  ('A.6.5', 'iso27001:A.6.5'),
  ('A.6.5', 'nis2:21.2.i'),
  ('A.6.6', 'iso27001:A.6.6'),
  ('A.6.6', 'nis2:21.2.i'),
  ('A.6.7', 'iso27001:A.6.7'),
  ('A.6.7', 'nis2:21.2.g'),
  ('A.6.8', 'iso27001:A.6.8'),
  ('A.6.8', 'nis2:21.2.b'),
  ('A.7.1', 'iso27001:A.7.1'),
  ('A.7.1', 'nis2:21.2.i'),
  ('A.7.2', 'iso27001:A.7.2'),
  ('A.7.2', 'nis2:21.2.i'),
  ('A.7.3', 'iso27001:A.7.3'),
  ('A.7.4', 'iso27001:A.7.4'),
  ('A.7.5', 'iso27001:A.7.5'),
  ('A.7.5', 'nis2:21.2.c'),
  ('A.7.6', 'iso27001:A.7.6'),
  ('A.7.7', 'iso27001:A.7.7'),
  ('A.7.7', 'nis2:21.2.g'),
  ('A.7.8', 'iso27001:A.7.8'),
  ('A.7.9', 'iso27001:A.7.9'),
  ('A.7.9', 'nis2:21.2.i'),
  ('A.7.10', 'iso27001:A.7.10'),
  ('A.7.10', 'nis2:21.2.i'),
  ('A.7.11', 'iso27001:A.7.11'),
  ('A.7.11', 'nis2:21.2.c'),
  ('A.7.12', 'iso27001:A.7.12'),
  ('A.7.13', 'iso27001:A.7.13'),
  ('A.7.13', 'nis2:21.2.e'),
  ('A.7.14', 'iso27001:A.7.14'),
  ('A.7.14', 'nis2:21.2.i'),
  ('A.8.1', 'iso27001:A.8.1'),
  ('A.8.1', 'nis2:21.2.g'),
  ('A.8.2', 'iso27001:A.8.2'),
  ('A.8.2', 'nis2:21.2.i'),
  ('A.8.3', 'iso27001:A.8.3'),
  ('A.8.3', 'nis2:21.2.i'),
  ('A.8.4', 'iso27001:A.8.4'),
  ('A.8.5', 'iso27001:A.8.5'),
  ('A.8.5', 'nis2:21.2.j'),
  ('A.8.6', 'iso27001:A.8.6'),
  ('A.8.7', 'iso27001:A.8.7'),
  ('A.8.7', 'nis2:21.2.g'),
  ('A.8.8', 'iso27001:A.8.8'),
  ('A.8.8', 'nis2:21.2.e'),
  ('A.8.9', 'iso27001:A.8.9'),
  ('A.8.9', 'nis2:21.2.e'),
  ('A.8.10', 'iso27001:A.8.10'),
  ('A.8.10', 'nis2:21.2.i'),
  ('A.8.11', 'iso27001:A.8.11'),
  ('A.8.12', 'iso27001:A.8.12'),
  ('A.8.13', 'iso27001:A.8.13'),
  ('A.8.13', 'nis2:21.2.c'),
  ('A.8.14', 'iso27001:A.8.14'),
  ('A.8.14', 'nis2:21.2.c'),
  ('A.8.15', 'iso27001:A.8.15'),
  ('A.8.15', 'nis2:21.2.b'),
  ('A.8.16', 'iso27001:A.8.16'),
  ('A.8.16', 'nis2:21.2.b'),
  ('A.8.17', 'iso27001:A.8.17'),
  ('A.8.18', 'iso27001:A.8.18'),
  ('A.8.19', 'iso27001:A.8.19'),
  ('A.8.19', 'nis2:21.2.e'),
  ('A.8.20', 'iso27001:A.8.20'),
  ('A.8.20', 'nis2:21.2.j'),
  ('A.8.21', 'iso27001:A.8.21'),
  ('A.8.21', 'nis2:21.2.j'),
  ('A.8.22', 'iso27001:A.8.22'),
  ('A.8.23', 'iso27001:A.8.23'),
  ('A.8.23', 'nis2:21.2.g'),
  ('A.8.24', 'iso27001:A.8.24'),
  ('A.8.24', 'nis2:21.2.h'),
  ('A.8.25', 'iso27001:A.8.25'),
  ('A.8.25', 'nis2:21.2.e'),
  ('A.8.26', 'iso27001:A.8.26'),
  ('A.8.26', 'nis2:21.2.e'),
  ('A.8.27', 'iso27001:A.8.27'),
  ('A.8.27', 'nis2:21.2.e'),
  ('A.8.28', 'iso27001:A.8.28'),
  ('A.8.28', 'nis2:21.2.e'),
  ('A.8.29', 'iso27001:A.8.29'),
  ('A.8.29', 'nis2:21.2.e'),
  ('A.8.29', 'nis2:21.2.f'),
  ('A.8.30', 'iso27001:A.8.30'),
  ('A.8.30', 'nis2:21.2.d'),
  ('A.8.30', 'nis2:21.2.e'),
  ('A.8.31', 'iso27001:A.8.31'),
  ('A.8.31', 'nis2:21.2.e'),
  ('A.8.32', 'iso27001:A.8.32'),
  ('A.8.32', 'nis2:21.2.e'),
  ('A.8.33', 'iso27001:A.8.33'),
  ('A.8.34', 'iso27001:A.8.34');

commit;
